export {default as Home} from "./Home.js";
export {default as PlayerFinder} from "./PlayerFinder.js";
export {default as TeamFinder} from "./TeamFinder.js";
export {default as Glossary} from "./Glossary.js";
export {default as Navigation} from "./Navigation.js";
export {default as Analysis} from "./Analysis";
export {default as Teamdetails} from "./Teamdetails";
export {default as PlayerDetails} from "./PlayerDetails";
export {default as TSAnalysis} from "./TSAnalysis"
export {default as Shotcharts} from "./Shotcharts"
export {default as Login} from "./Authentication/Login"
export {default as Register} from "./Authentication/Register"
export {default as Dashboard} from "./Dashboard"
export {default as Teamstats} from "./Teamstats"